---

AWSTemplateFormatVersion: '2010-09-09'

Description: Enables multiple AWS Config Rules in AWS Organization

Mappings: {}

Parameters: {}

Resources:

  AWSConfigServiceIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSConfigRole
  
  # To enable AWS Config, you must create a configuration recorder 
  # and a delivery channel
  # You must create a configuration recorder before you can create or update a Config rule. 
  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties: 
      Name: TestConfigRecorder
      RecordingGroup: 
        AllSupported: True
      # Might need a service linked role
      # !Ref AWSConfigServiceIAMRole does not work for RoleARN property  
      RoleARN: arn:aws:iam::810347228369:role/aws-service-role/config.amazonaws.com/AWSServiceRoleForConfig
 
  ConfigDeliveryChannel: 
    Type: AWS::Config::DeliveryChannel
    Properties: 
      ConfigSnapshotDeliveryProperties: 
        DeliveryFrequency: One_Hour
      Name: TestDeliveryChannel
      S3BucketName: deliverychannel

  RootUserMFAEnabledConfigRule:
    Type: AWS::Config::ConfigRule
    Properties:  
      ConfigRuleName: RootUserMFARule
      Description: Is MFA Enabled for Root User?
      MaximumExecutionFrequency: One_Hour
      # can create own rules via lambda or have a list of managed rules here:
      # https://docs.aws.amazon.com/config/latest/developerguide/managed-rules-by-aws-config.html
      Scope: 
        ComplianceResourceTypes: []
      Source:
        Owner: AWS
        SourceIdentifier: ROOT_ACCOUNT_MFA_ENABLED
    DependsOn: ConfigRecorder  
