version: '3'
services:
  web:
    build: ./web/
    ports:
     - "5000:5000"
    links:
      - mysql
  mysql:
    build: ./mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: visits