---
AWSTemplateFormatVersion: '2010-09-09'

Description: Create an VPC that exports resources allowing a VPN to be built

Parameters: {}

Mappings: {}

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref VPC

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet

  VPNGateway:
    # note that a stack can create multiple VPN Gateways but only one VPN Gateway 
    # can be attached at any given time
    # appending a unique identifier ("01") in the event that multiple VPN Gateways
    # need to be created may be a good idea - I've opted not to do this in this
    # particular template
    Type: AWS::EC2::VPNGateway
    Properties:
      Type: ipsec.1

  VPCGatewayAttachment01:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      VpcId: !Ref VPC
      VpnGatewayId: !Ref VPNGateway

Outputs:

  PrivateRouteTableId:
    Description: PrivateRouteTableId
    Export:
      Name: vpc-PrivateRouteTableId
    Value: !Ref PrivateRouteTable

  VPNGatewayId:
    Description: VPNGatewayId
    Export:
      Name: vpc-VPNGatewayId
    Value: !Ref VPNGateway
